### PR TITLE
Iotivity constrained

### PR DESCRIPTION
**Pull request by jprestwo**

### CODE REVIEW

**Comment by poussa** [comment]
Tested the branch (on linux), it works beautifully. On the same machine the OcfServer.js and OcfClient.js can talk. 

I also tested against https://github.com/01org/iot-rest-api-server

It also works:

`$ npm i iot-rest-api-server`
`$ cd iot-rest-api-server/`
`$ node index.js`

On separate terminal: 

`$ cd test/`
`$ ./oic-get /res`
`localhost:8000 /res`
```json
[{"di":"30303030-3030-3030-2d30-3030302d3030","links":[{"href":"/oic/p","rt":"oic.wk.p","if":"oic.if.r"}]},{"di":"30303030-3030-3030-2d30-3030302d3030","links":[{"href":"/light/1","rt":"oic.r.light","if":"oic.if.rw"}]}]
HTTP: 200
```
`spoussa:test$ ./oic-get "/light/1?di=30303030-3030-3030-2d30-3030302d3030"`
`localhost:8000 /light/1?di=30303030-3030-3030-2d30-3030302d3030`
```json
{"properties":{"state":true}}
HTTP: 200
```

**Comment by poussa** [comment]
@jprestwo if you are okay, I'd like to merge this PR so we can have wider testing.

**Comment by poussa** [comment]
Actually, the A101 Zephyr build fails:

```
/home/spoussa/src/iot/zephyr.js/src/zjs_promise.c: In function 'post_promise':
/home/spoussa/src/iot/zephyr.js/src/zjs_promise.c:47:13: error: unused variable 'i' [-Werror=unused-variable]
         int i;
             ^
cc1: all warnings being treated as errors
/home/spoussa/src/iot/zephyr.js/deps/zephyr/scripts/Makefile.build:182: recipe for target 'src/zjs_promise.o' failed
```

**Comment by poussa** [comment]
@jprestwo can you try to run the PR at least one Zephyr board, like FRDM it is makes it easier.

**Comment by poussa** [comment]
Also the [Makefile] patch needs to be dropped since it is already in master and devel.

**Comment by poussa** [comment]
@gabrielschulhof @zolkis @nagineni PTAL, at least the .js samples

**Comment by jprestwo** [comment]
@poussa:

I fixed the A101 build problem as well as removed the other commit (not sure how that got there in the first place). Unfortunately I am having a build problem for the K64 (sent an email about it), but as soon as I get that sorted out I can test on that platform.

File: samples/OcfClient.js [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+print("Started OCF client");
+
+client.on('error', function(error) {
+  if (error.deviceId)
+    print("Error for device: " + error.deviceId);
+});
+
+function onupdate(resource) {
+    print("Resource updated:");
```
Comment (kenchris) [inline samples/OcfClient.js]: We don't have console.log ?

File: samples/OcfClient.js [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    print("    deviceId: " + resource.deviceId);
+    print("    resourcePath: " + resource.resourcePath);
+    if (resource.properties != undefined) {
```
Comment (kenchris) [inline samples/OcfClient.js]: !==

File: samples/OcfClient.js [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+            anotherInt: 333,
+            anotherString: "another string"
+        };
+        resource.array = ["test1", "test2", "test3", "test4", "test5"];
+        resource.intArray = [1, 2, 3, 4, 5, 6];
+
+        client.update(resource).then(function(resource) {
+            print("update successful");
+        }).catch(function(error) {
+            print("Error updating name='" + error.name + "' message='" + error.message + "' " + "code=" + error.errorCode);
```
Comment (kenchris) [inline samples/OcfClient.js]: two lines?

File: samples/OcfClientUpdate.js [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+    if (resource.properties != undefined) {
+        print("Resource property 'state' is " + resource.properties.state);
+    } else {
+        print("resource.properties not found");
+    }
+}
+
+client.on('update', onupdate);
+
+var light_state = true;
```
Comment (kenchris) [inline samples/OcfClientUpdate.js]: lightState, but a state needs a state value... true is not such one

lightOn could be ok, or it should be lightState = "lights-on" or similar

File: samples/OcfClientUpdate.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+        resource.state = light_state;
+        client.update(resource).then(function(resource) {
+            print("update successful");
+            client.retrieve(resource.deviceId, {observable: false}).then(function(res) {
+                print("retrieve() was successful, deviceId=" + res.deviceId);
+            }).catch(function(error) {
+                print("retrieve() returned an error: " + error.name);
+            });
+        }).catch(function(error) {
+            print("Error updating name='" + error.name + "' message='" + error.message + "' " + "code=" + error.errorCode);
```
Comment (kenchris) [inline samples/OcfClientUpdate.js]: two lines, doesn't even fit on github

File: samples/OcfPlatformInfo.js [hunk 6]
```diff
@@ -0,0 +1,35 @@
...
+    print("Resource found: path=" + resource.resourcePath + " id=" + resource.deviceId);
+
+    client.getPlatformInfo(resource.deviceId).then(function(info) {
+        print("Got platform info for: " + info.id);
+    }).catch(function(error) {
+        print("Error getting platform info: " + error.name);
+    });
+}
+
+client.findResources({resourceType:"oic.r.light"}, found).then(function(resource) {
```
Comment (kenchris) [inline samples/OcfPlatformInfo.js]: spacing

File: samples/OcfServer.js [hunk 7]
```diff
@@ -0,0 +1,51 @@
+var server = require('ocf').server;
+
+print("Started OCF server");
+
+var MyProperties = {
+	state: true
```
Comment (kenchris) [inline samples/OcfServer.js]: too much indentation in this file

**Comment by jprestwo** [comment]
@kenchris, latest commit has the sample changes.

**Comment by poussa** [comment]
@jprestwo Did you have any luck with K64F platform?

**Comment by jprestwo** [comment]
@poussa, no, I have not got the K64 build to compile yet. I am looking more into it right now, just had to do some rebase's on my PR's this morning. Unfortunately even the master/devel branches don't compile for me with a fresh git checkout.

**Comment by poussa** [comment]
@jprestwo I think something went wrong in the rebase since now I see the promise build error again. It was fixed at some point.

**Comment by jprestwo** [comment]
@poussa, your right, the rebase put that line back in. Just got that fixed. Regarding the K64 build problem, I am going to do a git bisect and figure out what commit changed it, because it used to build fine, and all the Zephyr samples I have tried to build just now seem to build without that error.

**Comment by poussa** [comment]
@jprestwo thanks for the update, the promise works now. I am seeing an build error on F64K platform in your branch:

```
src/main.c:90:15: error: implicit declaration of function 'strnlen' [-Werror=implicit-function-declaration]
         len = strnlen(script_gen, MAX_SCRIPT_SIZE);
````

But you need https://github.com/01org/zephyr.js/pull/283 to fix it.

**Comment by jprestwo** [comment]
@poussa, ok, once #283 is merged I will rebase this PR. I went back VERY far in the git history and still see the same problem. From what I can find online it is something to do with the flag: `-mfloat-abi=hard`. When I build with `V=1` I see that flag defined for every source file I saw, and when I run the ARM gcc variant with this flag `-print-multi-lib` it says that hard float ABI is enabled by default... so as far as I can tell everything is using hardware floating point, yet it is still giving this error. This seems to be something specific to my system and no one else is seeing this error, plus Zephyr samples all build correctly so the Zephyr guys may not be much help.

**Comment by poussa** [comment]
@jprestwo #283 has been merged last week, just rebase and you'll have it. Once there, my build hits another know issue https://github.com/01org/zephyr.js/issues/160. It is Zephyr SDK issue which will be fixed in next SDK release. Seems that your problem is not seen anywhere else.

**Comment by poussa** [comment]
@jprestwo which Zephyr SDK you have? Update to 0.8.2 in case you have something different.

**Comment by jprestwo** [comment]
@poussa, #283 has been merged to master, it needs to be cherry-picked into devel. @grgustaf, could you cherry-pick that (or some other way of getting it to the devel branch?).

#160 was the same issue I am having, but I updated to SDK version 0.8.2 and it seems to have fixed the problem, I am able to build on master.

File: samples/OcfClient.js [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+        client.update(resource).then(function(resource) {
+            print("update successful");
+        }).catch(function(error) {
+            print("Error updating name='" + error.name + "' message='" + 
+                    error.message + "' " + "code=" + error.errorCode);
+        });
+    }, 1000);
+}
+
+client.findResources({resourceType:"oic.r.light"}, found).then(function(resource) {
```
Comment (kenchris) [inline samples/OcfClient.js]: usually we whould have spaces after  { and before } and after :

File: samples/OcfDeviceInfo.js [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+    print("Resource found: path=" + resource.resourcePath + " id=" + resource.deviceId);
+
+    client.getDeviceInfo(resource.deviceId).then(function(info) {
+        print("Got device info for: " + info.uuid);
+    }).catch(function(error) {
+        print("Error getting device info: " + error.name);
+    });
+}
+
+client.findResources({ resourceType:"oic.r.light" }, found).then(function(resource) {
```
Comment (kenchris) [inline samples/OcfDeviceInfo.js]: space after :

Comment (kenchris) [inline samples/OcfDeviceInfo.js]: You should look through all of these

**Comment by jprestwo** [comment]
@poussa,

I took out the OCF build for the K64 and A101 because there are some patches that are required for some iotivity dependencies. TinyCBOR defines `STRINGIFY`, `likely`, and `unlikely` and provides no way to compile out and/or un-define them. I will figure out how to submit a patch to that project and wrap the defines in an ifdef e.g. 
```
#ifndef STRINGIFY
#define STRINGIFY
#endif
```
Do we want to merge this, leaving out the A101/K64 build (for OCF only), or wait until I can land a patch in TinyCBOR?

**Comment by poussa** [comment]
@jprestwo can you fix the travis errors. Let's get this PR moving again.

I am getting a different build error than travis. For some reason the iotivity-constrained include path is not in compiler flags:

```
  /opt/zephyr-sdk/sysroots/i686-pokysdk-linux/usr/bin/iamcu-poky-elfiamcu/i586-poky-elfiamcu-gcc -Wp,-MD,src/.main.o.d  -nostdinc -isystem /opt/zephyr-sdk/sysroots/i686-pokysdk-linux/usr/bin/iamcu-poky-elfiamcu/../../lib/iamcu-poky-elfiamcu/gcc/i586-poky-elfiamcu/5.2.1/include -isystem /opt/zephyr-sdk/sysroots/i686-pokysdk-linux/usr/bin/iamcu-poky-elfiamcu/../../lib/iamcu-poky-elfiamcu/gcc/i586-poky-elfiamcu/5.2.1/include-fixed -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/arch/x86/include -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/arch/x86/soc/intel_quark/quark_se -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/boards/x86/arduino_101  -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/include -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/include -I/home/spoussa/src/iot/zephyr.js/outdir/arduino_101/include/generated -I/home/spoussa/src/iot/zephyr.js/outdir/arduino_101/misc/generated/sysgen -include /home/spoussa/src/iot/zephyr.js/outdir/arduino_101/include/generated/autoconf.h  -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/ext/hal/qmsi/include -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/ext/hal/qmsi/drivers/include -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/ext/hal/qmsi/soc/quark_se/include/ -I /opt/zephyr-sdk/sysroots/iamcu-poky-elfiamcu/usr/include  -I/home/spoussa/src/iot/zephyr.js/src -Isrc -DKERNEL -c -g -std=c99 -fno-asynchronous-unwind-tables -Wall -Wno-format-zero-length -Wno-main -ffreestanding -Os -fno-stack-protector -fno-omit-frame-pointer -ffunction-sections -fdata-sections -mpreferred-stack-boundary=2 -mno-sse -march=lakemont -mtune=lakemont -msoft-float -miamcu -Wno-unused-but-set-variable -fno-reorder-functions -fno-defer-pop -Wno-pointer-sign -fno-strict-overflow -Werror=implicit-int -Wall -Werror -D_XOPEN_SOURCE=700   -I/home/spoussa/src/iot/zephyr.js/deps/jerryscript/jerry-core   -I/home/spoussa/src/iot/zephyr.js/deps/zephyr/drivers   -I/home/spoussa/src/iot/zephyr.js/outdir/include -DZJS_POOL_CONFIG -DBUILD_MODULE_OCF    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(main)"  -D"KBUILD_MODNAME=KBUILD_STR(main)" -c -o src/main.o /home/spoussa/src/iot/zephyr.js/src/main.c
In file included from /home/spoussa/src/iot/zephyr.js/src/main.c:29:0:
/home/spoussa/src/iot/zephyr.js/src/zjs_ocf_common.h:8:20: fatal error: oc_api.h: No such file or directory
compilation terminated.
```

**Comment by jprestwo** [comment]
@poussa, unfortunately things have changed quite a bit since this PR was started. After upgrading Zephyr and JerryScript, OCF does not work in a number of different ways. Not only that but updating to the latest iotivity-constrained git repo led to some problems as well. I am working through them but this isn't going to be a  "quick and easy" merge unfortunatly

**Comment by jprestwo** [comment]
@poussa, with some patches I was able to get this building for the freedom board. It will run but I have no been able to actually make any OCF connections because I am not setup correctly with my own router and such, so it *could* work on the FRDM board but I am not sure yet. I have it rebased to devel but had to add a hack in that applies patches to tinycbor/iotivity-constrained in order for it to build for the freedom board due to its strict compile options.

**Comment by pfalcon** [comment]
> it could work on the FRDM board but I am not sure yet

How is it supposed to work at all? Is there some external BLE adapter or builtin Ethernet used?

**Comment by jprestwo** [comment]
@pfalcon, the FRDM-K64F has a built-in ethernet adapter. When I run one of the OCF samples it starts up without any errors, but at work I am unable to connect to it because I am on the corporate network.

**Comment by pfalcon** [comment]
@jprestwo : Yep, FRDM is what I have (I don't have Arduino 101, sometimes I consider that maybe I should get it, but I guess approach "That thing is for arduino_101? Nope, don't have it, let's work on something generic which works for any board" will be more productive longer term ;-) ).

So, if there will be any instructions, I'll be happy to test this iotivity thing on my FRDM. My personal outlook of the current (master) IP stack of Zephyr is that it's severely broken and not worth a time - I spent a sleepless week (after a normal-schedule month) trying to produce a working networking demo with it a month ago. But I used TCP (MQTT+TLS specifically), my understanding is that iotivity uses UDP-based protocols, maybe that works better. Otherwise, I look towards starting to use new IP stack from "net" Zephyr branch. To that end, my patch to convert FRDM's ethernet driver for new stack was merged today. I'll be interested to work on generic networking support for Z.js, will submit RFC on that later.

**Comment by jprestwo** [comment]
@poussa,

I have two patches, one into iotivity-constrained, and the other into TinyCBOR to fix the compiler issues I am seeing. Currently I have the build setup to apply said patches before it builds the OCF bindings.
tinycbor: https://github.com/01org/tinycbor/pull/53
iotivity-constrained: https://gerrit.iotivity.org/gerrit/#/c/13979/

**Comment by jprestwo** [comment]
@pfalcon, this latest push should support the Freedom board. I can't test it ATM but it builds differently than it was before (security was the problem, I think). So if you have time to try it out, it should hopefully work.

**Comment by pfalcon** [comment]
@jprestwo: Thanks, in my queue.

**Comment by jprestwo** [comment]
@poussa, @grgustaf, @kenchris, @jimmy-huang, @brianjjones,

This PR is finally good to go and Travis is happy with it. It has also been updated with the callback ring buffer change. If we could just do a final review on this we could finally get this merged!

Thanks.

**Comment by poussa** [comment]
Good. I'll do a quick test tomorrow.

**Comment by poussa** [comment]
On Linux, builds and works fine. OcfClient.js and talk to OcfServer.js

However, I was not able to build for arduino 101:

````
make JS=samples/OcfServer.js
...
  CC      src/main.o
In file included from /home/spoussa/src/iot/zephyr.js/src/main.c:29:0:
/home/spoussa/src/iot/zephyr.js/src/zjs_ocf_common.h:8:20: fatal error: oc_api.h: No such file or directory
compilation terminated.
```

Travis seems to be happy so my issue should not block the merging but we need to figure out what is the issue since other folks may hit it ass well.

+1 for merging now.

**Comment by jprestwo** [comment]
@poussa, the reason for that was because I had a conditional in the Makefile which would not build for the A101 which was put in a while ago when I was only building for Linux. I removed that conditional now, but iotivity-constrained is too big to fit on the A101 anyways, so the A101 build will still not succeed if you try to build with OcfServer.js/OcfClient.js.

File: arc/src/main.c [hunk 10]
```diff
@@ -333,7 +333,7 @@ static void handle_glcd(struct zjs_ipm_message* msg)
         buffer = msg->data.glcd.buffer;
         if (!buffer) {
             error_code = ERROR_IPM_INVALID_PARAMETER;
-            PRINT("buffer not found\n");
+            ZJS_PRINT("buffeZJS_PRINT found\n");
```
Comment (grgustaf) [inline arc/src/main.c]: oops

File: Makefile [hunk 11]
```diff
@@ -123,18 +129,19 @@ endif
...
 # Explicit clean
 .PHONY: clean
-clean:
-	@if [ -d deps/jerryscript ]; then \
-		make -C $(JERRY_BASE) -f targets/zephyr/Makefile clean BOARD=$(BOARD); \
-		rm -rf deps/jerryscript/build/$(BOARD)/; \
-		rm -rf deps/jerryscript/build/lib; \
-	fi
-	@if [ "$(TARGET)" != "linux" ]; then \
+clean: update
```
Comment (grgustaf) [inline Makefile]: Since I found at least one other thing to comment about, how about add a comment here as to why you're doing this - so we're more likely to be able to clean it up later. Namely, this update makes clean work on a brand new repo.

**Comment by grgustaf** [comment]
+1
